In [63]:
import glob
import os
import re
import numpy as np

import torch
from torch.utils.data import Dataset
from tqdm import tqdm

import config
from utils import load_image

In [64]:
path = f"../input/reduced_dataset/00000/FLAIR/*"
files = sorted(
    glob.glob(path),
    key=lambda var: [
        int(x) if x.isdigit() else x for x in re.findall(r"[^0-9]|[0-9]+", var)
    ],
)

In [65]:
len(files)

202

In [66]:
image_numbers = []
for image_path in files:

    match = re.search(r"Image-(\d+).png", image_path)
    if match:
        image_numbers.append(int(match.group(1)))

# Sort the image numbers and find the median.
image_numbers.sort()
start = image_numbers[0]
middle = image_numbers[len(image_numbers) // 2]

In [67]:
middle

190

In [68]:
# # middle = len(files) // 2
num_imgs2 = 64 // 2
p1 = max(start, middle - num_imgs2)
p2 = min(len(files), middle + num_imgs2)
image_stack = [load_image(f) for f in files[p1:p2]]

In [69]:
p1

158

In [70]:
p2

202

In [71]:
image_stack

[array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32),
 array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32),
 array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32),
 array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],


In [72]:
img3d = np.stack(image_stack).T
if img3d.shape[-1] < 32:
    n_zero = np.zeros((112, 112, 32 - img3d.shape[-1]))
    img3d = np.concatenate((img3d, n_zero), axis=-1)

In [73]:
np = np.expand_dims(img3d, 0)

In [75]:
np.shape

(1, 112, 112, 44)